version: '3.8'

services:
  network_goods:
    build: 
      context: ./network_goods
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  orders:
    build: 
      context: ./orders
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    networks:
      - app-network

networks:
  app-network:

